# Generated by Django 4.2.4 on 2023-08-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('age', models.IntegerField(default=18, null=True)),
                ('designation', models.CharField(choices=[('manager', 'Manager'), ('trainee', 'Trainee'), ('intern', 'Intern')], default='manager', max_length=20)),
            ],
        ),
    ]
