# Generated by Django 4.2.4 on 2023-08-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demofeature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('salary', models.BigIntegerField(default=None, null=True)),
                ('age', models.IntegerField(default=18, null=True)),
                ('designation', models.CharField(choices=[('manager', 'Manager'), ('trainee', 'Trainee'), ('intern', 'Intern')], default='manager', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='DemoModel',
        ),
    ]
